### PR TITLE
Uppercase XML Elements

### PR DESCRIPTION
**Pull request by kcotugno**
We've had some problems with our code breaking do to certain elements requiring uppercase. All Intacct Api example are in this format so, let's make sure all elements are made uppercase.

This needs QA.

### CODE REVIEW

**Comment by kcotugno** [comment]
@arincon9 Do we still want to do this?

**Comment by arincon9** [comment]
@kcotugno I think it is a good idea, I would like to QA to make sure that it still accepts those that don't require capitalization.

**Review by arincon9 — APPROVED** [review]
LGTM

**Comment by kcotugno** [comment]
@arincon9 I'm going to close. If we run into the issue again we can reopen.

**Pull request closed without merging**
